name: Release App

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./src-tauri/tauri.conf.json').package.version")" >> $GITHUB_ENV
      - name: create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            return data.id

  build-tauri:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            arch: x86_64
            rust_target: x86_64-unknown-linux-gnu
            name: 'Only for Ubuntu'
          - os: macos-latest
            arch: x86_64
            rust_target: x86_64-apple-darwin
            name: 'Only for MacOS x86_64'
          - os: macos-latest
            arch: aarch64
            rust_target: aarch64-apple-darwin
            name: 'Only for MacOS aarch64'
          - os: windows-latest
            arch: x86_64
            rust_target: x86_64-pc-windows-msvc
            name: 'Only for Windows'
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: check release title
        id: check-title
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ needs.create-release.outputs.release_id }}
            })
            if (data.name.includes('Only for') && !data.name.includes('${{ matrix.config.name }}')) {
              console.log('Skipping build for this configuration')
              console.log('Release title:', data.name)
              console.log('Configuration:', '${{ matrix.config.name }}')
              return 'skip';
            }
            return 'continue';
      - name: Print result
        run: echo "The result is ${{ steps.check-title.outputs.result }}"
      - uses: actions/checkout@v3
        if: steps.check-title.outputs.result == '"continue"'
      - name: setup node
        uses: actions/setup-node@v3
        if: steps.check-title.outputs.result == '"continue"'
        with:
          node-version: 18
          cache: 'yarn'
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        if: steps.check-title.outputs.result == '"continue"'
        with:
          targets: ${{ matrix.config.rust_target }}
      - uses: Swatinem/rust-cache@v2
        if: steps.check-title.outputs.result == '"continue"'
        with:
          key: ${{ matrix.config.rust_target }}
      - name: install dependencies (ubuntu only)
        if: matrix.config.os == 'ubuntu-latest' && steps.check-title.outputs.result == '"continue"'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        if: steps.check-title.outputs.result == '"continue"'
        run: yarn install # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        if: steps.check-title.outputs.result == '"continue"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [create-release, build-tauri]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
